language: php
sudo: false

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_VERSION='5.0.*'
    - php: 7.3
      env: SYMFONY_VERSION='5.0.*'

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

cache:
  directories:
    - $HOME/.composer/cache

install: COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - ./vendor/bin/phing build

after_success:
  - travis_retry php vendor/bin/php-coveralls
