language: php

jobs:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION='4.4.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2
      env: SYMFONY_VERSION='4.4.*'
    - php: 7.2
      env: SYMFONY_VERSION='5.0.*'
    - php: 7.2
    - php: 7.3
      env: SYMFONY_VERSION='4.4.*'
    - php: 7.3
      env: SYMFONY_VERSION='5.0.*'
    - php: 7.3
    - php: 7.4
      env: SYMFONY_VERSION='4.4.*'
    - php: 7.4
      env: SYMFONY_VERSION='5.0.*'
    - php: 7.4
    - php: nightly

  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

cache:
  directories:
    - $HOME/.composer/cache

install: COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - composer tests

after_success:
  - travis_retry php vendor/bin/php-coveralls
