image:
  name: bestitdocker/build:pipelines
  username: $DOCKER_HUB_USER
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_MAIL

pipelines:
  default:
    - step:
        script:    
          - composer -n install -o --prefer-dist
          - ./vendor/bin/phing build
