services:
    best_it_feature_toggle.bag.stash_bag:
        class: BestIt\FeatureToggleBundle\Bag\StashBag

    best_it_feature_toggle.manager.feature_manager:
        class: BestIt\FeatureToggleBundle\Manager\FeatureManager
        arguments:
            - '@best_it_feature_toggle.bag.stash_bag'

    best_it_feature_toggle.twig.toggle_extension:
        class: BestIt\FeatureToggleBundle\Twig\ToggleExtension
        arguments:
            - '@best_it_feature_toggle.manager.feature_manager'
        tags:
            - { name: twig.extension }

    best_it_feature_toggle.listener.annotation_subscriber:
        class: BestIt\FeatureToggleBundle\Listener\AnnotationSubscriber
        arguments:
            - '@annotations.reader'
            - '@best_it_feature_toggle.manager.feature_manager'
        tags:
            - { name: kernel.event_subscriber }

    best_it_feature_toggle.stash.config_stash:
        class: BestIt\FeatureToggleBundle\Stash\ConfigStash
        tags:
            - { name: best_it_feature_toggle.stash, priority: 0 }

    best_it_feature_toggle.profiler.feature_data_collector:
        class: BestIt\FeatureToggleBundle\Profiler\FeatureDataCollector
        arguments:
            - '@best_it_feature_toggle.bag.stash_bag'
        tags:
            -
                name:     data_collector
                template: '@BestItFeatureToggle/profiler/layout.html.twig'
                id:       'best_it_feature_toggle.profiler.feature_data_collector'
        public: false

    best_it_feature_toggle.listener.route_subscriber:
        class: BestIt\FeatureToggleBundle\Listener\RouteSubscriber
        arguments: ['@best_it_feature_toggle.manager.feature_manager']
        tags:
            - { name: kernel.event_subscriber }